apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: abdm-callback-proxy
    environment: default
  name: abdm-callback-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abdm-callback-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: abdm-callback-proxy
        environment: default
    spec:
      containers:
        - image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          name: abdm-callback-proxy
          imagePullPolicy: Always
      restartPolicy: Always