apiVersion: v1
kind: Service
metadata:
  name: abdm-callback-proxy
spec:
  ports:
    - name: '9099'
      port: 9099
      targetPort: 80
  selector:
    app: abdm-callback-proxy
    environment: default
  type: ClusterIP