name: Deploy

on:
  push:
    branches:
      - main
      - BAH-2192
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v1
        with:
           node-version: "16.x"
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: bahmniindiadistro/abdm-callback-proxy:${{github.run_number}},bahmniindiadistro/abdm-callback-proxy:latest

